language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
    api_key:
      secure: Idbp9MctqYPhhiIPTPTfx2rLW3aspJPzT4d8O9krfHyjQNaBD7aaAodKeH1gTtsuG32G95eTJKfvDgHYMNP5xsV2OTQqO/wXtxDI4k6lk7PEL7thtjaj5LaOjQQqj26Stmt2FgBZETFf1vPrJ52e81Rk6Pvq1UgJbRmrr9xFQbTiQxMZEYpH47ek8J1cAsNl1yIzcoAHT0sT/EQJe2kr5MXybmBlC4d7W5MPboQz+uVGl+Ai+sYpaKuPzokqLGFvsQzIxPNFy7zKHvqr505CfUzINS+s3v5hmWTWZGfQ5qlPXDIq7uYItKvuAMX9gtlCwxgWSflvs3IIk5d6dKp0Bs5HBX6MyAciKPm5QhAAUDSZLm8uxdkU1fkNS/leVGQooS/o2ShwzYs+k4H7Q9HjR5OD4GQ9zdk9alWN0eKA+h4Mg+nLDGxr7H9/WJdNYIoxGhXJm429R5zY9NpKDiu1vLjqd2bkYFS7s9r9Bsw5yy72uZckgFQoWVo4Evz01YRNYdAT6GuCild7L/Hw44NW3VKFYWnyHc8qbTSEFWmMeIeQRvlpfprz4PEhaSemK08QxFD5EL7HXKBND8As0/2VSaPmMU4YvJDFCQWQEW0gldfAHR8c8gmcnQdsEUHCruVAvSTpoKnKEK4lWk7W4rMyzBXslJbtpeqE8rM6DdVs4VM=
  app: jobquest-fe
  on:
    repo: jobQuest/jobquest-fe
    branch: main
  skip-cleanup: true
